services:
  vote:
    build:
      context: ./vote
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - appnet

  result:
    build:
      context: ./result
    ports:
      - "5001:8888"
    depends_on:
      - db
    networks:
      - appnet

  worker:
    build:
      context: ./worker
    depends_on:
      - db
      - redis
    networks:
      - appnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - appnet

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  db-data:
  redis-data:

networks:
  appnet:
    external: true